name: Compilar documento LaTeX

on:
  push:
    paths:
      - '**.tex'
      - '**.bib'
      - '**.sty'
      - '**.cls'
      - '**.png'
      - '**.jpg'
      - '**.pdf'
      - '**.eps'
  workflow_dispatch:

permissions:
  contents: write  # 🔑 Permite hacer push al repositorio

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Entrar al repositorio
        uses: actions/checkout@v3

      - name: Instalar dependencias de LaTeX
        run: |
          sudo apt-get update
          sudo apt-get install -y texlive-latex-recommended texlive-latex-extra latexmk texlive-lang-spanish

      - name: Compilar Integracion.tex
        run: |
          latexmk -pdf -shell-escape -interaction=nonstopmode -halt-on-error -f Integracion.tex

      - name: Configurar Git
        run: |
          git config --global user.name "Victor Garcia"
          git config --global user.email "victor.garcia@cimat.mx"
