name: Compilar documento LaTeX

on:
  push:
    paths:
      - '**.tex'
      - '**.bib'
      - '**.sty'
      - '**.cls'
      - '**.png'
      - '**.jpg'
      - '**.pdf'
      - '**.eps'
  workflow_dispatch:

permissions:
  contents: write  # 🔑 Permite hacer push al repositorio

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Entrar al repositorio
        uses: actions/checkout@v3

      - name: Instalar dependencias de LaTeX
        run: |
          sudo apt-get update
          sudo apt-get install -y texlive-latex-recommended texlive-latex-extra latexmk texlive-lang-spanish

      - name: Compilar archivo Integracion.tex
        run: latexmk -pdf -interaction=nonstopmode Integracion.tex

      - name: Verificar existencia de Integracion.pdf
        run: test -f Integracion.pdf

      - name: Configurar Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Subir Integracion.pdf al repositorio
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git add Integracion.pdf
          git commit -m "Actualizar Integracion.pdf compilado automáticamente" || echo "Sin cambios"
          git push https://x-access-token:${TOKEN}@github.com/${{ github.repository }} HEAD:${{ github.ref_name }}
