name: Compilar documento LaTeX

on:
  push:
    paths:
      - '**.tex'
      - '**.bib'
      - '**.sty'
      - '**.cls'
      - '**.png'
      - '**.jpg'
      - '**.pdf'
      - '**.eps'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar el repositorio
        uses: actions/checkout@v3

      - name: Instalar dependencias de LaTeX
        run: |
          sudo apt-get update
          sudo apt-get install -y texlive-full latexmk
          sudo apt-get install -y texlive-tkz tkz-doc

      - name: Compilar Integracion.tex
        run: |
          latexmk -pdf -shell-escape -interaction=nonstopmode -halt-on-error Integracion.tex

      - name: Configurar Git
        run: |
          git config --global user.name "Victor Garcia"
          git config --global user.email "victor.garcia@cimat.mx"

      - name: Subir Integracion.pdf al repositorio
        run: |
          git add Integracion.pdf
          git commit -m "Actualizar Integracion.pdf compilado automáticamente"
          git push
